### ISSUE TITLE
没有Content Page?

### ISSUE THREAD

**Issue by TheMasterOfMagic** [Liam0205/mcmthesis#12]
Introduction之前的Content Page不见了? 这个难道不是必须的吗?
虽然可以自己手动用/tableofcontents加上, 但是它默认style和整个模板其他部分不统一, 会显得格格不入.
能不能考虑加上呢?

**Comment by Liam0205** [comment]
@TheMasterOfMagic Content Page 说的是目录？

美赛论文不必须有目录。若要有目录，可自行修改。若要提 feature request，请给出美赛官方文档，以说明美赛论文需要有目录，以及说明目录的格式要求。
