### ISSUE TITLE
Does mcmthesis Template has a memo template? How to write a memo?

### ISSUE THREAD

**Issue by vangohao** [Liam0205/mcmthesis#13]

**Comment by Liam0205** [comment]
@vangohao Yes, the latest version of ``mcmthesis`` has a predefined ``memo`` environment. You could download the latest version of ``mcmthesis`` from the release page.

**Comment by Liam0205** [comment]
See: https://github.com/Liam0205/mcmthesis/blob/master/mcmthesis.dtx#L322-L335
