### ISSUE TITLE
summary page已更新+CTAN安装遇上点小问题

### ISSUE THREAD

**Issue by Alexhaoge** [Liam0205/mcmthesis#18]
CTAN上已经更新为6.3，支持2020年的新版summary page
感谢更新，star必须安排上！
我安装这个最新版的时候遇到一个小问题
在编译xelatex mcmthesis.dtx时遇到报错：
! Package doc Error: Checksum not passed (526<>529).
![报错](https://user-images.githubusercontent.com/53772038/73383740-e3437300-4304-11ea-84b9-18700d1a2194.png)
解决方法是修改这个文件中149行的CheckSum为529
不知道这个问题是不是我自己电脑的个例

**Comment by latexstudio** [comment]
校验的问题， 感谢！
