### ISSUE TITLE
能否在下一版采用BibTex生成参考文献？

### ISSUE THREAD

**Issue by sukanka** [Liam0205/mcmthesis#4]
如题，最新的模板*6.2和6.2.1*都是手动输入参考文献。但是如果能使用**BibTex**，添加参考文献就会方便很多。首先在mcm-thesis文件夹下新建thesis-ref.bib文件。再在mcmthesis-demo.tex文件添加代码如下：

`\usepackage[hyperref=true,backend=biber,sorting=none,backref=true]{biblatex} %添加对bibtex的支持`
`\addbibresource{thesis-ref.bib}   %参考文献所在文件为 thesis-ref.bib`

在附录(Appendix)之前插入：

`\nocite{*}		%这里是参考文献`
`\printbibliography`

之后只需要在**thesis-ref.bib**添加参考文献就可以了，具体过程参考[这里](https://www.zhihu.com/question/23565739/answer/51511029)

**Comment by Liam0205** [comment]
欢迎提 PR。
