### ISSUE TITLE
mistakes in doc

### ISSUE THREAD

**Issue by Gsllchb** [Liam0205/mcmthesis#6]
在该项目提供的[教程](https://liam0205.me/2016/01/27/how-to-use-mcmthesis/)中有几处错误。在
* 摘要页中的标题 / titleinsheet
* 摘要页中的关键字 / keywordsinsheet
* 标题页 / titlepage
* 标题页中的摘要 / abstract
中，错误地将`\mcmsetup`写成了`\mcmthesis`,导致无法通过编译。

**Comment by Liam0205** [comment]
感谢指出，已修正。
