### ISSUE TITLE
minor mistake in doc

### ISSUE THREAD

**Issue by Gsllchb** [Liam0205/mcmthesis#7]
在您的网站上的一篇LaTeX教程上有一个小错误。
链接：https://liam0205.me/2014/09/08/latex-introduction/
在`分段函数`那一部分，在`\ begin`之间多了一个空格。

**Comment by Liam0205** [comment]
同样感谢，也已修正。

2018-02-02 16:59 GMT+08:00 Gsllchb <notifications@github.com>:

**Comment by Liam0205** [comment]
博客相关问题，建议到 [Liam0205/Liam0205.github.io](https://github.com/Liam0205/liam0205.github.io) 提相关 issue，感谢~！
